sudo: required
dist: focal
language: python
python:
  - "3.8"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq pkg-config fuse3
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf
install:
  - sudo apt-get install cmake make gcc
  - sudo apt-get install libfuse3-dev
  #- sudo apt-get install meson ninja-build
  #- ./travis_install.sh
  #- cmake .
  - make
script: ./test
